name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start Redis v5
      uses: superchargejs/redis-github-action@1.1.0
      with:
        redis-version: 5

    - run: npm install
    - run: npm run build --if-present
    - run: cp .env.example .env
    - run: npm test
      env:
        CI: true
    - run: npm run lint
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
  